spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

system.authentication.password=${SYSTEM_AUTH_PASSWORD}
system.encryption.key=${SYSTEM_ENCRYPTION_KEY}

finki.akreditacii.subject-url-prefix=https://akreditacii.dev.finki.ukim.mk/subject

server.error.include-exception=true
server.error.include-message=always

studentsThreshold=10

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
